### PR TITLE
Install composer

### PR DESCRIPTION
**Pull request by baloran**
I think it would be interesting to add composer to the dockerfile.

### CODE REVIEW

**Comment by kasperisager** [comment]
What would be the use-case for this?

**Comment by baloran** [comment]
The use case can be: 
- Install Symfony
- Work with other people and share our librairies we use

and some others cases!

**Comment by kasperisager** [comment]
I'd personally much prefer doing both of those things on the host and not within container.

**Comment by baloran** [comment]
Its not weird to be this on the host? Its not better to use the docker bash ?

**Comment by kasperisager** [comment]
The project is meant to provide a simple setup where one boots up the containers and then forget that they even exist. It's extremely rare that I touch the containers, much less run a bash process within them. I do all development and associated tooling on the host and then use the containers only for running the code.

**Comment by baloran** [comment]
Ok, I do it on my fork :)

**Pull request closed without merging**
